# Generated by Django 5.2.3 on 2025-06-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0002_matricula_aluno_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('anoRegistro', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, choices=[('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=20, null=True)),
            ],
        ),
    ]
