# Generated by Django 5.2.3 on 2025-06-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0004_professores'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('codigo_curso', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidade', models.CharField(choices=[('Semipresencial', 'semipresencial'), ('online', 'Online'), ('presencial', 'Presencial')], max_length=20)),
                ('carga_horaria', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
