# Generated by Django 5.2.3 on 2025-06-22 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0005_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('semipresencial', 'Semipresencial'), ('online', 'Online'), ('presencial', 'Presencial')], max_length=20),
        ),
        migrations.CreateModel(
            name='coordenador',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.curso')),
            ],
        ),
    ]
