# Generated by Django 5.2.3 on 2025-06-23 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0007_aluno_turma_alter_aluno_cpf_alter_turma_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_total', models.CharField(max_length=4)),
                ('nota_aluno', models.CharField(max_length=4)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.aluno')),
            ],
        ),
    ]
