# Generated by Django 5.2.3 on 2025-06-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0008_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplina', models.CharField(max_length=15)),
                ('nome_disciplina', models.CharField(max_length=15)),
                ('carga_horaria', models.IntegerField(max_length=4)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.turma')),
            ],
        ),
        migrations.CreateModel(
            name='frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateField(verbose_name='Data:')),
                ('presenca_aluno', models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('justificada', 'Justificada')], max_length=15)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.aluno')),
            ],
        ),
    ]
