# Generated by Django 5.2.3 on 2025-06-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0008_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateField(verbose_name='Data:')),
                ('presenca_aluno', models.CharField(choices=[('justificada', 'Justificada'), ('presente', 'Presente'), ('falta', 'Falta')], max_length=15)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.aluno')),
            ],
        ),
    ]
