# Generated by Django 5.2.3 on 2025-06-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0009_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='presenca_aluno',
            field=models.CharField(choices=[('falta', 'Falta'), ('presente', 'Presente'), ('justificada', 'Justificada')], max_length=15),
        ),
        migrations.CreateModel(
            name='disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplina', models.CharField(max_length=15)),
                ('nome_disciplina', models.CharField(max_length=15)),
                ('carga_horaria', models.IntegerField(max_length=4)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.turma')),
            ],
        ),
        migrations.AddField(
            model_name='professores',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.disciplina'),
        ),
    ]
