# Generated by Django 5.2.3 on 2025-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0011_alter_frequencia_presenca_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='presenca_aluno',
            field=models.CharField(choices=[('presente', 'Presente'), ('justificada', 'Justificada'), ('falta', 'Falta')], max_length=15),
        ),
    ]
