# Generated by Django 5.2.3 on 2025-06-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0012_alter_frequencia_presenca_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='presenca_aluno',
            field=models.CharField(choices=[('falta', 'Falta'), ('justificada', 'Justificada'), ('presente', 'Presente')], max_length=15),
        ),
    ]
